name: Build and publish Docker images for devcontainer

on: push

jobs:
  build-and-publish:
    strategy:
      matrix:
        include:
          - debian: buster
            python: 3
          - debian: bullseye
            python: 3
          - debian: bookworm
            python: 3
          - debian: bookworm
            python: 3.12

    runs-on: ubuntu-latest
        
    steps:
    - name: checkout
      uses: actions/checkout@v4
    # - name: Set up Docker Buildx
    #   uses: docker/setup-buildx-action@v3
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        context: .devcontainer
        push: false
        build-args: |
          DEBIAN=${{ matrix.debian }}
          PYTHON=${{ matrix.python }}
        tags: musicalninjarandint/gpiozero-devcontainer:${{ matrix.debian }}-${{ matrix.python }}
